spring:
   http:
     encoding:
       force: true
       charset: utf-8
       enabled: true
# 模板引擎
   thymeleaf:
      mode: LEGACYHTML5
      encoding: utf-8
# 禁用缓存
      cache: false
      content-type: text/html
# 资源信息
   messages:
# 国际化资源文件路径
      basename: static/i18n/messages
   jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
   profiles:
      active: druid
# 文件上传
   servlet:
      multipart:
# 单个文件大小
         max-file-size: 10MB
# 设置总上传的文件大小
         max-request-size: 20MB
# 服务模块
#   devtools:
#      restart:
# 热部署开关
#         enabled: true